[program:whiteboard]
command=node /app/tools/whiteboard/server.mjs
user=deck
environment=DATA_DIR="/data/whiteboard",PORT="8102"
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
