[program:links]
command=/app/tools/links/links
user=deck
environment=DATA_DIR="/data/links",LISTEN="127.0.0.1:8106",PUBLIC_URL="%(ENV_PUBLIC_URL)s",MAX_LINKS="%(ENV_MAX_LINKS)s"
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
