"""Mirage: is this image or video AI-generated? Evidence first, guesses last.

What is checked, in order of reliability:
  1. Content Credentials (C2PA) and the IPTC "digital source type": a signed
     statement that the file was made by a generator (or captured by a camera).
  2. Generator metadata left behind: Stable Diffusion / ComfyUI / NovelAI
     PNG text, Midjourney, Firefly, DALL·E and friends in EXIF/XMP.
  3. The invisible DWT-DCT watermark of the Stable Diffusion reference
     pipelines ("SDV2", and the SDXL bit pattern).
  4. Camera fingerprints (make, model, exposure) - easy to forge, but
     their absence on a supposedly phone-shot JPEG is a hint.
  5. Dimensions typical of generators (weak).
  6. Optional: a statistical score from the Sightengine "genai" model, when
     SIGHTENGINE_USER / SIGHTENGINE_SECRET are set.
"""
from __future__ import annotations

import base64
import importlib.util
import io
import json
import os
import re
import shutil
import subprocess
import sysconfig
from typing import Any

import numpy as np
from PIL import Image

IMAGE_EXT = {".jpg", ".jpeg", ".png", ".webp", ".heic", ".heif", ".tif", ".tiff", ".avif", ".bmp", ".gif"}
VIDEO_EXT = {".mp4", ".mov", ".m4v", ".webm", ".mkv", ".avi", ".mts", ".3gp"}

GENERATORS = [
    # (regex on lowercase text, label)
    (r"midjourney", "Midjourney"), (r"stable[ -]?diffusion|stablediffusion", "Stable Diffusion"), (r"sdxl", "Stable Diffusion XL"),
    (r"dall[·\-]?e", "DALL·E"), (r"openai", "OpenAI"), (r"adobe firefly|firefly", "Adobe Firefly"), (r"\bimagen\b", "Google Imagen"),
    (r"ideogram", "Ideogram"), (r"leonardo\.ai|leonardo ai", "Leonardo.ai"), (r"\bflux\b", "Flux"), (r"comfyui", "ComfyUI"),
    (r"automatic1111|a1111|stable diffusion web ?ui", "AUTOMATIC1111"), (r"invokeai", "InvokeAI"), (r"fooocus", "Fooocus"),
    (r"novelai", "NovelAI"), (r"bing image creator|image creator", "Bing Image Creator"), (r"microsoft designer", "Microsoft Designer"),
    (r"\bsora\b", "OpenAI Sora"), (r"runway", "Runway"), (r"pika labs|pika\.art", "Pika"), (r"kling", "Kling"), (r"luma ?ai|dream machine", "Luma"),
    (r"\bveo\b", "Google Veo"), (r"gen-?[23]\b", "Runway Gen"), (r"playground ?ai|playground\.com", "Playground"), (r"nightcafe", "NightCafe"),
    (r"craiyon", "Craiyon"), (r"dreamstudio", "DreamStudio"), (r"getimg", "getimg.ai"), (r"generated by ai|ai[- ]generated|généré par (une )?ia", "mention « généré par IA »"),
]
GEN_SIZES = {512, 576, 640, 704, 768, 832, 896, 960, 1024, 1088, 1152, 1216, 1280, 1344, 1408, 1472, 1536, 1600, 1664, 1728, 1792, 1856, 1920, 1984, 2048}
SDV2 = b"SDV2"
SDXL_BITS = [int(b) for b in "101100111110110010010000011110111011000110011110"]


def exiftool(path: str) -> dict[str, Any]:
    """All metadata as one flat dict of 'Group:Tag' -> value (numbers unformatted)."""
    if not shutil.which("exiftool"):
        return {}
    try:
        out = subprocess.run(["exiftool", "-j", "-G1", "-n", "-api", "largefilesupport=1", "-x", "SourceFile", path],
                             capture_output=True, text=True, timeout=60, check=False).stdout
        data = json.loads(out or "[]")
        return data[0] if data else {}
    except (subprocess.SubprocessError, json.JSONDecodeError, OSError):
        return {}


def ffprobe(path: str) -> dict[str, Any]:
    if not shutil.which("ffprobe"):
        return {}
    try:
        out = subprocess.run(["ffprobe", "-v", "error", "-print_format", "json", "-show_format", "-show_streams", path],
                             capture_output=True, text=True, timeout=60, check=False).stdout
        return json.loads(out or "{}")
    except (subprocess.SubprocessError, json.JSONDecodeError, OSError):
        return {}


def extract_frames(path: str, workdir: str, count: int = 3) -> list[str]:
    """A few JPEG frames spread over the video, for image-level checks."""
    info = ffprobe(path)
    try:
        duration = float(info.get("format", {}).get("duration") or 0)
    except (TypeError, ValueError):
        duration = 0
    frames = []
    for i in range(count):
        t = duration * (0.1 + 0.8 * i / max(count - 1, 1)) if duration else i
        out = os.path.join(workdir, f"frame{i}.jpg")
        r = subprocess.run(["ffmpeg", "-v", "error", "-y", "-ss", f"{t:.2f}", "-i", path, "-frames:v", "1", "-q:v", "3", out],
                           capture_output=True, timeout=120, check=False)
        if r.returncode == 0 and os.path.exists(out):
            frames.append(out)
    return frames


# ---------------------------------------------------------------- C2PA

def read_c2pa(path: str) -> dict[str, Any] | None:
    """Content Credentials, through the c2pa library when it is installed."""
    try:
        import c2pa  # type: ignore
    except ImportError:
        return None
    try:
        reader = c2pa.Reader(path)
        store = json.loads(reader.json())
    except Exception:  # noqa: BLE001 - no manifest, or an unreadable one
        return None
    return parse_store(store)


def parse_store(store: dict) -> dict[str, Any] | None:
    """Summarise a C2PA manifest store (the JSON the c2pa library returns)."""
    active = store.get("active_manifest")
    manifests = store.get("manifests") or {}
    m = manifests.get(active) or (next(iter(manifests.values())) if manifests else None)
    if not m:
        return None
    actions, source_types, agents = [], [], []
    for a in m.get("assertions") or []:
        label = a.get("label", "")
        data = a.get("data") or {}
        if label.startswith("c2pa.actions"):
            for act in data.get("actions") or []:
                actions.append(act.get("action", ""))
                st = act.get("digitalSourceType") or ""
                if st:
                    source_types.append(st.rsplit("/", 1)[-1])
                agent = act.get("softwareAgent")
                if isinstance(agent, dict):
                    agent = agent.get("name")
                if agent:
                    agents.append(str(agent))
    status = store.get("validation_status") or []
    errors = [s.get("code", "") for s in status if "error" in str(s.get("code", "")).lower() or s.get("explanation")]
    return {
        "present": True,
        "valid": not errors,
        "errors": errors[:5],
        "generator": m.get("claim_generator_info", [{}])[0].get("name") if m.get("claim_generator_info") else m.get("claim_generator"),
        "title": m.get("title"),
        "actions": actions[:12],
        "source_types": sorted(set(source_types)),
        "agents": sorted(set(agents))[:8],
        "ingredients": len(m.get("ingredients") or []),
    }


# ---------------------------------------------------------------- Stable Diffusion watermark

_dwt = None


def _dwt_module():
    """imwatermark's DWT-DCT codec, loaded from its file so the package
    __init__ (which drags in torch for RivaGAN) never runs."""
    global _dwt
    if _dwt is not None:
        return _dwt or None
    _dwt = False
    # 0.2.x ships the algorithm as maxDct.EmbedMaxDct, 0.1.x as dwtDct.EmbedDwtDct: same codec.
    for site in {sysconfig.get_paths().get("purelib"), sysconfig.get_paths().get("platlib")}:
        for fname, cls in (("maxDct.py", "EmbedMaxDct"), ("dwtDct.py", "EmbedDwtDct")):
            candidate = os.path.join(site or "", "imwatermark", fname)
            if not site or not os.path.exists(candidate):
                continue
            spec = importlib.util.spec_from_file_location("mirage_" + fname[:-3], candidate)
            mod = importlib.util.module_from_spec(spec)
            try:
                spec.loader.exec_module(mod)
                mod.Codec = getattr(mod, cls)
                _dwt = mod
                break
            except Exception:  # noqa: BLE001
                _dwt = False
        if _dwt:
            break
    return _dwt or None


def _bgr(path: str, max_side: int = 2048) -> np.ndarray | None:
    try:
        img = Image.open(path)
        img.load()
        if max(img.size) > max_side:  # the watermark survives downscaling poorly, but huge images are slow
            img.thumbnail((max_side, max_side))
        arr = np.asarray(img.convert("RGB"))
        return arr[:, :, ::-1].copy()
    except Exception:  # noqa: BLE001
        return None


def sd_watermark(path: str) -> dict[str, Any] | None:
    mod = _dwt_module()
    bgr = _bgr(path)
    if mod is None or bgr is None or min(bgr.shape[:2]) < 64:
        return None
    try:
        dec = mod.Codec(watermarks=[], wmLen=32, scales=[0, 36, 36], block=4)
        bits = dec.decode(bgr)
        raw = np.packbits(np.asarray(bits, dtype=np.uint8)).tobytes()
        if raw == SDV2:
            return {"scheme": "SDV2", "detail": "Filigrane invisible DWT-DCT « SDV2 » (Stable Diffusion 2.x)"}
        dec48 = mod.Codec(watermarks=[], wmLen=48, scales=[0, 36, 36], block=4)
        bits48 = [int(b) for b in dec48.decode(bgr)]
        if bits48 == SDXL_BITS:
            return {"scheme": "SDXL", "detail": "Filigrane invisible DWT-DCT de Stable Diffusion XL (diffusers)"}
    except Exception:  # noqa: BLE001
        return None
    return None


def embed_sd_watermark(src: str, dst: str) -> bool:
    """Used by the tests: stamp SDV2 the way the reference pipeline does."""
    mod = _dwt_module()
    bgr = _bgr(src)
    if mod is None or bgr is None:
        return False
    bits = [int(b) for byte in SDV2 for b in format(byte, "08b")]
    enc = mod.Codec(watermarks=bits, wmLen=32, scales=[0, 36, 36], block=4)
    out = enc.encode(bgr)
    Image.fromarray(out[:, :, ::-1]).save(dst, quality=95)
    return True


# ---------------------------------------------------------------- signals

def _text_blob(meta: dict[str, Any]) -> str:
    keys = [k for k in meta if re.search(r"software|creatortool|description|comment|parameters|prompt|workflow|title|creator|artist|source|history|agent|generator|label|keywords|subject|producer|encoder|handler", k, re.I)]
    return " ".join(str(meta[k]) for k in keys).lower()


def _first(meta: dict[str, Any], *names) -> Any:
    for n in names:
        for k, v in meta.items():
            if k.split(":", 1)[-1].lower() == n.lower():
                return v
    return None


def signals_from_metadata(meta: dict[str, Any], c2pa: dict | None, kind: str) -> list[dict]:
    out: list[dict] = []
    blob = _text_blob(meta)

    # 1. Content Credentials
    if c2pa and c2pa.get("present"):
        st = c2pa.get("source_types") or []
        ai = [s for s in st if "trainedalgorithmicmedia" in s.lower()]
        gen = c2pa.get("generator") or "outil inconnu"
        agents = ", ".join(c2pa.get("agents") or [])
        if ai:
            out.append({"id": "c2pa-ai", "strength": "proof", "title": "Content Credentials : média produit par une IA",
                        "detail": f"Manifeste C2PA signé par {gen}{' (' + agents + ')' if agents else ''}, type de source « {', '.join(ai)} »" + ("" if c2pa.get("valid") else " — signature non vérifiée")})
        elif any("digitalcapture" in s.lower() for s in st):
            out.append({"id": "c2pa-camera", "strength": "auth", "title": "Content Credentials : capture par un appareil",
                        "detail": f"Manifeste C2PA de {gen}, type de source « digitalCapture »" + ("" if c2pa.get("valid") else " — signature non vérifiée")})
        else:
            gl = (gen or "").lower() + " " + agents.lower()
            hit = next((label for rx, label in GENERATORS if re.search(rx, gl)), None)
            if hit:
                out.append({"id": "c2pa-gen", "strength": "proof", "title": f"Content Credentials signés par {hit}",
                            "detail": f"Manifeste C2PA : {gen}{' (' + agents + ')' if agents else ''}, actions {', '.join(c2pa.get('actions') or []) or '—'}"})
            else:
                out.append({"id": "c2pa", "strength": "info", "title": "Content Credentials présents",
                            "detail": f"Manifeste C2PA de {gen}, actions {', '.join(c2pa.get('actions') or []) or '—'}, {c2pa.get('ingredients', 0)} ingrédient(s)"})

    # 2. IPTC digital source type (Google, Adobe, some cameras write it too)
    dst = str(_first(meta, "DigitalSourceType") or "")
    if dst:
        short = dst.rsplit("/", 1)[-1]
        if "trainedalgorithmicmedia" in short.lower():
            out.append({"id": "iptc-ai", "strength": "proof", "title": "Marqueur IPTC : média produit par une IA", "detail": f"Digital Source Type = {short}"})
        elif "digitalcapture" in short.lower():
            out.append({"id": "iptc-camera", "strength": "auth", "title": "Marqueur IPTC : capture par un appareil", "detail": f"Digital Source Type = {short}"})
        else:
            out.append({"id": "iptc", "strength": "info", "title": "Marqueur IPTC de source", "detail": f"Digital Source Type = {short}"})

    # 3. Generator leftovers
    params = _first(meta, "Parameters")
    if params and re.search(r"steps:\s*\d+|sampler:|cfg scale", str(params), re.I):
        m = re.search(r"model(?: hash)?:\s*([^,\n]+)", str(params), re.I)
        out.append({"id": "sd-params", "strength": "proof", "title": "Métadonnées Stable Diffusion (AUTOMATIC1111 / Forge)",
                    "detail": "Bloc « parameters » avec prompt, sampler et CFG" + (f", modèle {m.group(1).strip()}" if m else "")})
    for key in ("Workflow", "Prompt"):
        v = _first(meta, key)
        if v and str(v).lstrip().startswith("{") and ("class_type" in str(v) or "KSampler" in str(v) or "nodes" in str(v)):
            out.append({"id": "comfy", "strength": "proof", "title": "Métadonnées ComfyUI", "detail": f"Graphe de nœuds embarqué dans le champ « {key} »"})
            break
    comment = str(_first(meta, "Comment", "UserComment") or "")
    if comment.lstrip().startswith("{") and re.search(r'"(prompt|uc|steps|sampler|seed)"', comment):
        out.append({"id": "novelai", "strength": "proof", "title": "Métadonnées de génération (NovelAI / SD)", "detail": "Commentaire JSON avec prompt, seed et sampler"})
    if re.search(r"job id|jobid", blob) and "midjourney" in blob:
        out.append({"id": "mj", "strength": "proof", "title": "Métadonnées Midjourney", "detail": "Prompt et identifiant de tâche embarqués"})
    seen = {s["id"] for s in out}
    for rx, label in GENERATORS:
        if re.search(rx, blob):
            key = "gen-" + re.sub(r"\W+", "", label.lower())
            if key in seen:
                continue
            seen.add(key)
            field = next((k for k in meta if re.search(rx, str(meta[k]).lower())), "métadonnées")
            out.append({"id": key, "strength": "strong" if label.startswith("mention") else "proof", "title": f"Mention de {label} dans les métadonnées", "detail": f"Champ {field}"})
            if len([s for s in out if s["id"].startswith("gen-")]) >= 3:
                break

    # 4. Camera fingerprint
    make, model = _first(meta, "Make"), _first(meta, "Model")
    exposure = _first(meta, "ExposureTime", "ShutterSpeedValue")
    fnumber, iso = _first(meta, "FNumber"), _first(meta, "ISO")
    lens = _first(meta, "LensModel", "LensInfo")
    if make or model:
        parts = [str(x) for x in (make, model) if x]
        extra = [f"f/{fnumber}" if fnumber else "", f"{exposure} s" if exposure else "", f"ISO {iso}" if iso else "", str(lens) if lens else ""]
        detail = " ".join(parts) + (" · " + ", ".join(e for e in extra if e) if any(extra) else "")
        out.append({"id": "camera", "strength": "auth" if (exposure or fnumber or iso) else "weak-auth", "title": "Empreinte d'appareil photo", "detail": detail + " — facile à copier, à ne pas prendre pour une preuve"})
    elif kind == "image" and str(_first(meta, "FileType") or "").upper() in ("JPEG", "HEIC", "HEIF"):
        out.append({"id": "no-exif", "strength": "weak", "title": "Aucune métadonnée d'appareil", "detail": "Un JPEG sorti d'un téléphone en a presque toujours ; un export de réseau social ou de générateur, non"})

    # 5. Dimensions
    w, h = _first(meta, "ImageWidth"), _first(meta, "ImageHeight")
    try:
        w, h = int(w), int(h)
    except (TypeError, ValueError):
        w = h = 0
    if kind == "image" and w and h and w in GEN_SIZES and h in GEN_SIZES and (w % 64 == 0 and h % 64 == 0):
        out.append({"id": "dims", "strength": "weak", "title": f"Dimensions typiques d'un générateur ({w}×{h})", "detail": "Multiples de 64 dans la plage des modèles de diffusion ; un recadrage ou un export peuvent aussi donner ça"})
    return out


def verdict_of(signals: list[dict], score: float | None) -> dict:
    proof = [s for s in signals if s["strength"] == "proof"]
    strong = [s for s in signals if s["strength"] == "strong"]
    weak = [s for s in signals if s["strength"] == "weak"]
    auth = [s for s in signals if s["strength"] == "auth"]
    if proof:
        return {"level": "ai", "label": "produit par une IA", "summary": f"{len(proof)} preuve{'s' if len(proof) > 1 else ''} directe{'s' if len(proof) > 1 else ''} : {proof[0]['title'].lower()}"}
    if strong or (score is not None and score >= 0.8):
        return {"level": "likely", "label": "très probablement une IA", "summary": (strong[0]["title"] if strong else f"score statistique de {round(score * 100)} %") + " — pas de preuve signée, mais des indices forts"}
    if score is not None and score >= 0.5:
        return {"level": "hints", "label": "indices d'IA", "summary": f"Score statistique de {round(score * 100)} % ; aucun marqueur dans le fichier"}
    if auth and (score is None or score < 0.3):
        return {"level": "camera", "label": "origine caméra déclarée", "summary": auth[0]["title"] + (f" · score statistique de {round(score * 100)} %" if score is not None else "") + " — une signature C2PA vaut preuve, une simple ligne EXIF non"}
    if weak and score is None:
        return {"level": "unknown", "label": "aucun marqueur, quelques indices faibles", "summary": "Rien de signé, rien de laissé par un générateur connu ; « " + weak[0]["title"].lower() + " » est un indice trop faible pour conclure"}
    if score is not None:
        return {"level": "unknown", "label": "rien ne l'indique", "summary": f"Aucun marqueur dans le fichier et un score statistique de {round(score * 100)} % — ce n'est pas une preuve d'authenticité"}
    return {"level": "unknown", "label": "aucun marqueur d'IA", "summary": "Rien de signé, rien de laissé par un générateur connu. Ça ne prouve pas l'authenticité : la plupart des générateurs ne signent rien et les métadonnées se retirent en un clic"}


# ---------------------------------------------------------------- summary of metadata

def summarise(meta: dict[str, Any], kind: str) -> dict[str, Any]:
    g = lambda *n: _first(meta, *n)  # noqa: E731
    out = {
        "type": g("FileType"), "mime": g("MIMEType"), "size": g("FileSize"),
        "width": g("ImageWidth"), "height": g("ImageHeight"),
        "software": g("Software", "CreatorTool", "Encoder", "HandlerDescription"),
        "created": g("DateTimeOriginal", "CreateDate", "MediaCreateDate", "ModifyDate"),
        "make": g("Make"), "model": g("Model"), "lens": g("LensModel"),
        "exposure": g("ExposureTime"), "fnumber": g("FNumber"), "iso": g("ISO"), "focal": g("FocalLength"),
        "gps": bool(g("GPSLatitude")),
        "color_profile": g("ProfileDescription"),
        "description": (str(g("ImageDescription", "Description", "Comment", "UserComment") or "")[:300] or None),
    }
    if kind == "video":
        out.update({"duration": g("Duration", "MediaDuration"), "fps": g("VideoFrameRate"), "codec": g("CompressorID", "CompressorName"), "audio": g("AudioFormat")})
    return {k: v for k, v in out.items() if v not in (None, "", False)}


def thumbnail(path: str, max_side: int = 480) -> str | None:
    try:
        img = Image.open(path)
        img.thumbnail((max_side, max_side))
        buf = io.BytesIO()
        img.convert("RGB").save(buf, "JPEG", quality=80)
        return "data:image/jpeg;base64," + base64.b64encode(buf.getvalue()).decode()
    except Exception:  # noqa: BLE001
        return None


def kind_of(filename: str, meta: dict[str, Any]) -> str:
    ext = os.path.splitext(filename.lower())[1]
    mime = str(_first(meta, "MIMEType") or "")
    if mime.startswith("video/") or ext in VIDEO_EXT:
        return "video"
    if mime.startswith("image/") or ext in IMAGE_EXT:
        return "image"
    return "other"


def analyse(path: str, filename: str, workdir: str, scorer=None) -> dict[str, Any]:
    """scorer(paths) -> float | None : optional external statistical model."""
    meta = exiftool(path)
    kind = kind_of(filename, meta)
    if kind == "other":
        raise ValueError("ni une image ni une vidéo reconnue")
    c2pa = read_c2pa(path)
    signals = signals_from_metadata(meta, c2pa, kind)
    frames: list[str] = []
    preview = None
    if kind == "image":
        wm = sd_watermark(path)
        if wm:
            signals.insert(0, {"id": "sd-watermark", "strength": "proof", "title": "Filigrane invisible de Stable Diffusion", "detail": wm["detail"]})
        preview = thumbnail(path)
        score_inputs = [path]
    else:
        frames = extract_frames(path, workdir)
        if frames:
            preview = thumbnail(frames[len(frames) // 2])
            for f in frames:
                wm = sd_watermark(f)
                if wm:
                    signals.insert(0, {"id": "sd-watermark", "strength": "strong", "title": "Filigrane Stable Diffusion sur une image extraite", "detail": wm["detail"]})
                    break
        score_inputs = frames
    score = None
    if scorer and score_inputs:
        try:
            score = scorer(score_inputs)
        except Exception as exc:  # noqa: BLE001
            signals.append({"id": "score-error", "strength": "info", "title": "Score statistique indisponible", "detail": str(exc)[:200]})
    if score is not None:
        level = "strong" if score >= 0.8 else "hint" if score >= 0.5 else "info"
        signals.append({"id": "score", "strength": level, "title": f"Score statistique : {round(score * 100)} % de probabilité d'IA",
                        "detail": "Modèle « genai » de Sightengine" + (" sur des images extraites de la vidéo" if kind == "video" else "") + " — un classifieur, pas une preuve"})
    order = {"proof": 0, "strong": 1, "hint": 2, "auth": 3, "weak-auth": 4, "weak": 5, "info": 6}
    signals.sort(key=lambda s: order.get(s["strength"], 9))
    return {
        "kind": kind,
        "file": {"name": filename, **summarise(meta, kind)},
        "verdict": verdict_of(signals, score),
        "signals": signals,
        "c2pa": c2pa,
        "score": score,
        "preview": preview,
        "frames": len(frames),
        "metadata": {k: (v if len(str(v)) <= 400 else str(v)[:400] + "…") for k, v in sorted(meta.items()) if not k.startswith("File:") or k in ("File:FileType", "File:MIMEType", "File:ImageWidth", "File:ImageHeight")},
    }
