[program:convert]
command=/app/tools/convert/convert
user=deck
environment=WORK_DIR="/tmp/convert",HOME="/tmp/convert-home",LISTEN="127.0.0.1:8104"
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
