[program:paste]
command=/app/tools/paste/paste
user=deck
environment=DATA_DIR="/data/paste",LISTEN="127.0.0.1:8101",PUBLIC_URL="%(ENV_PUBLIC_URL)s"
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
