[program:bookmarks]
command=/app/tools/bookmarks/bookmarks
user=deck
environment=DATA_DIR="/data/bookmarks",PORT="8109"
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
